# Generated by Django 3.2.14 on 2022-08-02 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_upload_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(db_index=True, default=None)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('ca_cert', models.TextField(null=True)),
                ('client_cert', models.TextField(null=True)),
                ('client_key', pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ('username', pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ('password', pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ('proxy_url', models.TextField(null=True)),
                ('proxy_username', pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ('proxy_password', pulpcore.app.models.fields.EncryptedTextField(null=True)),
                ('download_concurrency', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Download concurrency must be at least 1')])),
                ('max_retries', models.PositiveIntegerField(null=True)),
                ('total_timeout', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')])),
                ('connect_timeout', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')])),
                ('sock_connect_timeout', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')])),
                ('sock_read_timeout', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')])),
                ('headers', models.JSONField(blank=True, null=True)),
                ('rate_limit', models.IntegerField(null=True)),
            ],
            options={
                'default_related_name': 'remote_config',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='remote',
            name='remote_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remotes', to='core.remoteconfig'),
        ),
    ]
